openapi: "3.0.2"
info:
  description:
    Interfaz API de la Municipalidad Ciudad de San Luis - SIGEM Backend
  title: Municipalidad Ciudad de San Luis - SIGEM Backend
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /actuator/info:
    get:
      tags:
        - Info
      description: Información de compilación de la aplicación
      summary: Obtiene información de compilación de la aplicación
      responses:
        "200":
          description: Respuesta exitosa con información de compilación de la aplicación
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Build"
  /auth/login:
    post:
      tags:
        - Auth
      description: Permite la autenticación en la aplicación
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      summary: Iniciar sesión
      responses:
        "200":
          description:
            Inicio de sesión exitoso. Header con JWT y body con lista de
            permisos asociados al JWT
          content:
            application/json:
              schema:
                description: Permisos de administrador
                items:
                  example: NIVEL_3_MENU_LATERAL
                  type: string
                type: array
          headers:
            Authorization:
              $ref: "#/components/headers/Authorization"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMethodArgumentNotValidException"
          description: Argumentos no válidos
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorBadCredentials"
          description: Inicio de sesión fallido
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          description: Error inesperado
components:
  headers:
    Authorization:
      description: Token de autenticación
      schema:
        example:
          "Bearer
          eyJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvQ2l1ZGFkX3BlcnNvbmFfbGFzdE5hbWUiOiIiLCJ1c3VhcmlvQ2l1ZGFkX3BlcnNvbmFfZmlyc3ROYW1lIjoiIiwidXN1YXJpb19kbmkiOiIyNzE2NzE4NSIsInVzdWFyaW9DaXVkYWRfcGVyc29uYV9jdWlsIjoiIiwidXN1YXJpb19kaXNwbGF5bmFtZSI6Ik1hcnRpbiBWaWxsZWdhcyIsInVzdWFyaW9fdXNlck5hbWUiOiJtdmlsbGVnYXMiLCJzdWIiOiJtdmlsbGVnYXMiLCJpYXQiOjE3MzYzMzc4NjAsImV4cCI6MTczNjM4MTA2MH0.3Gxz_6885gIMFkUGPEweCJbl-FW_MFsINP1cFc3alYY"
        format: jwt
        type: string
  parameters:
    AuthorizationHeader:
      description: Token de autenticación
      in: header
      name: Authorization
      required: true
      schema:
        example:
          "Bearer
          eyJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvQ2l1ZGFkX3BlcnNvbmFfbGFzdE5hbWUiOiIiLCJ1c3VhcmlvQ2l1ZGFkX3BlcnNvbmFfZmlyc3ROYW1lIjoiIiwidXN1YXJpb19kbmkiOiIyNzE2NzE4NSIsInVzdWFyaW9DaXVkYWRfcGVyc29uYV9jdWlsIjoiIiwidXN1YXJpb19kaXNwbGF5bmFtZSI6Ik1hcnRpbiBWaWxsZWdhcyIsInVzdWFyaW9fdXNlck5hbWUiOiJtdmlsbGVnYXMiLCJzdWIiOiJtdmlsbGVnYXMiLCJpYXQiOjE3MzYzMzc4NjAsImV4cCI6MTczNjM4MTA2MH0.3Gxz_6885gIMFkUGPEweCJbl-FW_MFsINP1cFc3alYY"
        format: jwt
        type: string
  schemas:
    Build:
      properties:
        artifact:
          description: Nombre del artefacto
          example: "munsl_sigem_backend"
          type: string
        group:
          description: Grupo de organización de la aplicación
          example: "ar.gob.sanluislaciudad"
          type: string
        name:
          description: Nombre de la aplicación
          example: "munsl_sigem_backend"
          type: string
        time:
          description: Fecha de la compilación en formato ISO 8601
          example: "2024-01-04T15:30:00Z"
          type: string
        version:
          description: Versión de la aplicación
          example: "0.0.1-SNAPSHOT"
          type: string
      type: object
    Error:
      properties:
        detail:
          description: Descripción del problema
          example: "Descripción del problema"
          type: string
        instance:
          description: El endpoint donde el problema ocurrió
          example: "/"
          type: string
        status:
          description: HTTP status code
          example: 500
          type: integer
        title:
          description: Nombre del problema
          example: "Exception"
          type: string
        timestamp:
          description: Fecha en formato ISO 8601
          example: "2024-01-04T15:30:00Z"
          type: string
        trace:
          description: Identificador único opentelemetry TraceID
          example: "0c6a41e22fe6478cc391908406ca9b8d"
          type: string
        type:
          description:
            Documentación donde se explica claramente qué sucedió y por qué
          example: "about:blank"
          type: string
      type: object
    ErrorBadCredentials:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            detail:
              example: "Bad credentials"
            instance:
              example: "/auth/login"
            status:
              example: 401
            title:
              example: "BadCredentialsException"
    ErrorMethodArgumentNotValidException:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            detail:
              example: "Validation failed for argument[...]"
            status:
              example: 400
            title:
              example: "MethodArgumentNotValidException"
    LoginRequest:
      properties:
        password:
          description: Contraseña
          example: "XXX"
          maxLength: 128
          minLength: 3
          type: string
        username:
          description: Nombre de usuario del administrador o CUIT del ciudadano
          example: "23215487369"
          maxLength: 32
          minLength: 4
          type: string
      required:
        - password
        - username
      type: object
