cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET, POST, PUT, DELETE, PATCH
  allowed-headers: "*"
  allow-credentials: true
jwt:
  key: ${JWT_KEY}
  ttl: 43200 #seconds, 12 hours
logging:
  level:
    org.hibernate.SQL: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    build:
      enabled: true
spring:
  application:
    name: munsl_sigem_backend
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS DBO
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  hmac:
    salt: ${HMAC_SALT}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true