name: Increment Version and Tag

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$latest" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          if [ -z "$LATEST_TAG" ]; then
            echo "new_version=v0.1.0" >> $GITHUB_ENV
          else
            LATEST_TAG="${LATEST_TAG#v}" # Remove 'v' prefix
            IFS='.' read -r major minor patch <<< "$LATEST_TAG"
            patch=$((patch+1))
            echo "new_version=v$major.$minor.$patch" >> $GITHUB_ENV
          fi
        env:
          LATEST_TAG: ${{ env.latest_tag }}

      - name: Create new tag
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}

      - name: Output new version
        run: echo "New version is ${{ env.new_version }}"
